name = "gc-forms-solid-start"
compatibility_date = "2025-08-13"

[site]
bucket = "./dist/client"

[build]
command = "pnpm run build"


[vars]
API_BASE_URL = "https://gc-forms-solid-start.tim-arney.workers.dev"
